typedef char s8;
typedef unsigned char u8;
typedef int s32;
typedef unsigned int u32;
typedef short int s16;
typedef unsigned short int u16;
typedef const char cs8;
typedef float f32;
typedef double d64;
typedef const unsigned char cu8;
